Prepare for re-release
jitsi/jitsi-meet-react-sdk pull request #9
Opened 2022-03-01 11:40 UTC by mihhu

2022-03-01 12:00 UTC, saghul requested changes
Left a few minor comments, PTAL!

2022-03-01 12:00 UTC, saghul commented on README.md
> +Optional. Provides an isolated context and prefixes the room name.
This needs to be mandatory.

2022-03-01 12:00 UTC, saghul commented on README.md
> +###### `getIFrameRef`
Can you document the common properties separately, so we don't duplicate them?

2022-03-01 13:27 UTC, mihhu commented on package.json
> +        "watch": "^0.13.0"
I ran npm audit fix to get rid of some vulnerabilities and the latest watch seemed to be the problem https://snyk.io/test/npm/watch/1.0.2

2022-03-01 13:28 UTC, mihhu commented on example/jitsiMeeting/src/App.jsx
> +        debugger;
😨 sorry

2022-03-04 07:45 UTC, saghul commented on package.json
> +        "watch": "^0.13.0"
Thanks for being vigilant!

2022-03-04 07:46 UTC, saghul approved these changes

2022-03-04 07:54 UTC, merged